#!/srvr/cs3311psql/lib/php535/bin/php
<?php

require("a2.php");

$db = dbConnect(DB_CONNECTION);
// Insert code here
$actor_name = $argv[1];
$lower = $argv[2];
$upper = $argv[3];

// Get the id of the input actor
$id_query = "select id from actor where name ilike %s";
$actor_id = dbOneValue($db, mkSQL($id_query, $actor_name));

//First, try to find all actors with degree of separation of 1
//Sort by degrees of separation then by name
//
?>
