#!/srvr/cs3311psql/lib/php535/bin/php
<?php

require("a2.php");

$db = dbConnect(DB_CONNECTION);

$start_name = $argv[1];
$end_name = $argv[2];


//Reinitialise start name with proper grammar
$name_query = "select name from actor where name ilike %s";
$start_name = dbOneValue($db, mkSQL($name_query, $start_name));
$end_name = dbOneValue($db, mkSQL($name_query, $end_name));


//For given names, find their corresponding ids
$id_query = "select id from actor where name ilike %s";
$sql = mkSQL($id_query, $start_name);

$start_id = dbOneValue($db, $sql);

$sql = mkSQL($id_query, $end_name);

$end_id = dbOneValue($db, $sql);

// First, check for pathlen of 1
$len1 = <<<length1
		select * from e_movie_actor
		where start_actor = %d and end_actor = %d
length1;

$sql = mkSQL($len1, $start_id, $end_id);
$res = dbQuery($db, $sql);
$num_path_1 = pg_num_rows($res);


if ($num_path_1 != 0) {
	$string_array1 = array();
	while ($t = dbNext($res)) {
		// Given start_actor, movie and end_actor, retrieve relevant invo
		$movie_query = "select title, year from movie where id = %d";
		$sql = mkSQL($movie_query, $t[movie]);
		list($title, $year) = dbOneTuple($db, $sql);
		$str = "$start_name was in $title ($year) with $end_name";
		array_push($string_array1, $str);
	}
	sort($string_array1);
	$i = 1;
	foreach ($string_array1 as $a) {
		echo "$i. $a\n";
		$i = $i + 1;
	}
	exit();
}

// Now, search for length of 2

$len2 = <<<length2
select ma1.movie movie1, ma1.end_actor actor1, ma2.movie movie2
from E_movie_actor as ma1 join E_movie_actor as ma2 on (ma1.end_actor = ma2.start_actor)
where ma1.start_actor = %d and ma2.end_actor = %d;
length2;

$sql = mkSQL($len2, $start_id, $end_id);
$res = dbQuery($db, $sql);

$num_path_2 = pg_num_rows($res);
if ($num_path_2 != 0) {
	$string_array2 = array();
	while ($t = dbNext($res)) {
		$movie_query = "select title, year from movie where id = %d";
		$sql = mkSQL($movie_query, $t[movie1]);
		list($title1, $year1) = dbOneTuple($db, $sql);
		$sql = mkSQL($movie_query, $t[movie2]);
		list($title2, $year2) = dbOneTuple($db, $sql);

		//Now, get the corresponding actor info
		$name_query = "select name from actor where id = %d";
		$name = dbOneValue($db, mkSQL($name_query, $t[actor1]));


		$str = "$start_name was in $title1 "
        if (!is_null($year1)) {
            $str = $str . "($year1) ";
        }
        $str = $str . "with $name1; ";

		$str = $str . "$name1 was in $title2 "
        if (!is_null($year2)) {
            $str = $str . "($year2) ";
        }
        $str = $str . "with $end_name";
		array_push($string_array2, $str);
		
	}

	sort($string_array2);
	$i = 1;
	foreach ($string_array2 as $a) {
		echo "$i. $a\n";
		$i = $i + 1;
	}
	exit();
}

// Now, do paths of length 3
$len3 = <<<length3
select ma1.movie movie1, ma1.end_actor actor1, ma2.movie movie2, ma2.end_actor actor2, ma3.movie movie3
from E_movie_actor as ma1 join E_movie_actor as ma2 on (ma1.end_actor = ma2.start_actor)
						  join E_movie_actor as ma3 on (ma2.end_actor = ma3.start_actor)
where ma1.start_actor = %d and ma3.end_actor = %d;
length3;
$sql = mkSQL($len3, $start_id, $end_id);
$res = dbQuery($db, $sql);
$num_path_3 = pg_num_rows($res);
if ($num_path_3 != 0) {
	$string_array3 = array();
	while ($t = dbNext($res)) {
		$movie_query = "select title, year from movie where id = %d";
		list($title1, $year1) = dbOneTuple($db, mkSQL($movie_query, $t[movie1]));
		list($title2, $year2) = dbOneTuple($db, mkSQL($movie_query, $t[movie2]));
		list($title3, $year3) = dbOneTuple($db, mkSQL($movie_query, $t[movie3]));

		$name_query = "select name from actor where id = %d";
		$name1 = dbOneValue($db, mkSQL($name_query, $t[actor1]));
		$name2 = dbOneValue($db, mkSQL($name_query, $t[actor2]));

		$str = "$start_name was in $title1 "
        if (!is_null($year1)) {
            $str = $str . "($year1) ";
        }
        $str = $str . "with $name1; ";

        $str = "$name1 was in $title2 "
        if (!is_null($year2)) {
            $str = $str . "($year2) ";
        }
        $str = $str . "with $name2; ";

        $str = $str . "$name2 was in $title3 "
        if (!is_null($year3)) {
            $str = $str . "($year3) ";
        }
        $str = $str . "with $end_name";

		array_push($string_array3, $str);
	}
	sort($string_array3);
	$i = 1;
	foreach ($string_array3 as $a) {
		echo "$i. $a\n";
		$i = $i + 1;
	}
	exit();
}

$len4 = <<<length4
select ma1.movie movie1,
        ma1.end_actor actor1,
        ma2.movie movie2,
        ma2.end_actor actor2,
        ma3.movie movie3,
        ma3.end_actor actor3,
        ma4.movie movie4
from E_movie_actor as ma1 join E_movie_actor as ma2 on (ma1.end_actor = ma2.start_actor)
						  join E_movie_actor as ma3 on (ma2.end_actor = ma3.start_actor)
						  join E_movie_actor as ma4 on (ma3.end_actor = ma4.start_actor)
where ma1.start_actor = %d and ma4.end_actor = %d;

length4;

$sql = mkSQL($len4, $start_id, $end_id);
$res = dbQuery($db, $sql);

$num_path_4 = pg_num_rows($res);

if ($num_path_4 != 0) {
    $string_array4 = array();
    while ($t = dbNext($res)) {
        // Get movie info
        $movie_query = "select title, year from movie where id = %d";
        list($title1, $year1) = dbOneTuple($db, mkSQL($movie_query, $t[movie1]));
        list($title2, $year2) = dbOneTuple($db, mkSQL($movie_query, $t[movie2]));
        list($title3, $year3) = dbOneTuple($db, mkSQL($movie_query, $t[movie3]));
        list($title4, $year4) = dbOneTuple($db, mkSQL($movie_query, $t[movie4]));

        // Now, get the names
        $name_query = "select name from actor where id = %d";
        $name1 = dbOneValue($db, mkSQL($name_query, $t[actor1]));
        $name2 = dbOneValue($db, mkSQL($name_query, $t[actor2]));
        $name3 = dbOneValue($db, mkSQL($name_query, $t[actor3]));

        //Combine into string
        $str = "$start_name was in $title1 "
        if (!is_null($year1)) {
            $str = $str . "($year1) ";
        }
        $str = $str . "with $name1; ";

        $str = "$name1 was in $title2 "
        if (!is_null($year2)) {
            $str = $str . "($year2) ";
        }
        $str = $str . "with $name2; ";

        $str = "$name2 was in $title3 "
        if (!is_null($year3)) {
            $str = $str . "($year3) ";
        }
        $str = $str . "with $name3; ";

        $str = $str . "$name3 was in $title4 "
        if (!is_null($year4)) {
            $str = $str . "($year4) ";
        }
        $str = $str . "with $end_name";
        array_push($string_array4, $str);

    }
    sort($string_array4);
    $i = 1;
    foreach ($string_array4 as $a) {
        echo "$i. $a\n";
        $i = $i + 1;

    }
    exit();

}

//Insert for length of 5
$len5 = <<<length5
	select ma1.movie movie1,
        ma1.end_actor actor1,
        ma2.movie movie2,
        ma2.end_actor actor2,
        ma3.movie movie3,
        ma3.end_actor actor3,
        ma4.movie movie4,
        ma4.end_actor actor4,
        ma5.movie movie5
from E_movie_actor as ma1 join E_movie_actor as ma2 on (ma1.end_actor = ma2.start_actor)
						  join E_movie_actor as ma3 on (ma2.end_actor = ma3.start_actor)
						  join E_movie_actor as ma4 on (ma3.end_actor = ma4.start_actor)
						  join E_movie_actor as ma5 on (ma4.end_actor = ma5.start_actor)
where ma1.start_actor = %d and ma5.end_actor = %d;
length5;
$sql = mkSQL($len5, $start_id, $end_id);
$res = dbQuery($db, $sql);
$num_path_5 = pg_num_rows($res);

if ($num_path_5 != 0) {
    $string_array5 = array();
    while ($t = dbNext($res)) {

        $movie_query = "select title, year from movie where id = %d";
        list($title1, $year1) = dbOneTuple($db, mkSQL($movie_query, $t[movie1]));
        list($title2, $year2) = dbOneTuple($db, mkSQL($movie_query, $t[movie2]));
        list($title3, $year3) = dbOneTuple($db, mkSQL($movie_query, $t[movie3]));
        list($title4, $year4) = dbOneTuple($db, mkSQL($movie_query, $t[movie4]));
        list($title5, $year5) = dbOneTuple($db, mkSQL($movie_query, $t[movie5]));

        // Now, get the names
        $name_query = "select name from actor where id = %d";
        $name1 = dbOneValue($db, mkSQL($name_query, $t[actor1]));
        $name2 = dbOneValue($db, mkSQL($name_query, $t[actor2]));
        $name3 = dbOneValue($db, mkSQL($name_query, $t[actor3]));
        $name4 = dbOneValue($db, mkSQL($name_query, $t[actor4]));

        $str = "$start_name was in $title1 "
        if (!is_null($year1)) {
            $str = $str . "($year1) ";
        }
        $str = $str . "with $name1; ";

        $str = "$name1 was in $title2 "
        if (!is_null($year2)) {
            $str = $str . "($year2) ";
        }
        $str = $str . "with $name2; ";

        $str = "$name2 was in $title3 "
        if (!is_null($year3)) {
            $str = $str . "($year3) ";
        }
        $str = $str . "with $name3; ";

        $str = "$name3 was in $title4 "
        if (!is_null($year4)) {
            $str = $str . "($year4) ";
        }
        $str = $str . "with $name4; ";

        $str = $str . "$name4 was in $title5 "
        if (!is_null($year5)) {
            $str = $str . "($year5) ";
        }
        $str = $str . "with $end_name";

        array_push($string_array5, $str);
    }
    sort($string_array5);
    $i = 1;
    foreach ($string_array5 as $a) {
        echo "$i. $a\n";
        $i = $i + 1;

    }
    exit();

}

//Insert for length of 6
$len6 = <<<length6
	select ma1.movie movie1,
        ma1.end_actor actor1,
        ma2.movie movie2,
        ma2.end_actor actor2,
        ma3.movie movie3,
        ma3.end_actor actor3,
        ma4.movie movie4,
        ma4.end_actor actor4,
        ma5.movie movie5,
        ma5.end_actor actor5,
        ma6.movie movie6

from E_movie_actor as ma1 join E_movie_actor as ma2 on (ma1.end_actor = ma2.start_actor)
						  join E_movie_actor as ma3 on (ma2.end_actor = ma3.start_actor)
						  join E_movie_actor as ma4 on (ma3.end_actor = ma4.start_actor)
						  join E_movie_actor as ma5 on (ma4.end_actor = ma5.start_actor)
						  join E_movie_actor as ma6 on (ma5.end_actor = ma6.start_actor)
where ma1.start_actor = %d and ma6.end_actor = %d;
length6;
$sql = mkSQL($len6, $start_id, $end_id);
$res = dbQuery($db, $sql);
$num_path_6 = pg_num_rows($res);

if ($num_path_6 != 0) {
	$string_array6 = array();
    while ($t = dbNext($res)) {
        // Get movie info
        $movie_query = "select title, year from movie where id = %d";
        list($title1, $year1) = dbOneTuple($db, mkSQL($movie_query, $t[movie1]));
        list($title2, $year2) = dbOneTuple($db, mkSQL($movie_query, $t[movie2]));
        list($title3, $year3) = dbOneTuple($db, mkSQL($movie_query, $t[movie3]));
        list($title4, $year4) = dbOneTuple($db, mkSQL($movie_query, $t[movie4]));
        list($title5, $year5) = dbOneTuple($db, mkSQL($movie_query, $t[movie5]));
        list($title6, $year6) = dbOneTuple($db, mkSQL($movie_query, $t[movie6]));

        // Now, get the names
        $name_query = "select name from actor where id = %d";
        $name1 = dbOneValue($db, mkSQL($name_query, $t[actor1]));
        $name2 = dbOneValue($db, mkSQL($name_query, $t[actor2]));
        $name3 = dbOneValue($db, mkSQL($name_query, $t[actor3]));
        $name4 = dbOneValue($db, mkSQL($name_query, $t[actor4]));
        $name5 = dbOneValue($db, mkSQL($name_query, $t[actor5]));

        //Combine into string
        $str = "$start_name was in $title1 "
        if (!is_null($year1)) {
            $str = $str . "($year1) ";
        }
        $str = $str . "with $name1; ";

        $str = "$name1 was in $title2 "
        if (!is_null($year2)) {
            $str = $str . "($year2) ";
        }
        $str = $str . "with $name2; ";

        $str = "$name2 was in $title3 "
        if (!is_null($year3)) {
            $str = $str . "($year3) ";
        }
        $str = $str . "with $name3; ";

        $str = "$name3 was in $title4 "
        if (!is_null($year4)) {
            $str = $str . "($year4) ";
        }
        $str = $str . "with $name4; ";

        $str = $str . "$name4 was in $title5 "
        if (!is_null($year5)) {
            $str = $str . "($year5) ";
        }
        $str = $str . "with $name5";

        $str = $str . "$name5 was in $title6 "
        if (!is_null($year6)) {
            $str = $str . "($year6) ";
        }
        $str = $str . "with $end_name";

        array_push($string_array6, $str);

    }
    sort($string_array6);
    $i = 1;
    foreach ($string_array6 as $a) {
        echo "$i. $a\n";
        $i = $i + 1;

    }
    exit();

}

// If reach here, no path exists

?>
